### ISSUE TITLE
Невозможно подписать файл

### ISSUE THREAD

**Issue by ddvlru** [bmakarenko/gost-crypto-gui#1]
После выбора файла для действий «Подписать файл» или «Зашифровать файл» в консоль выводится сообщение об ошибке:

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gostcryptogui/gui.py", line 250, in encrypt
    choose = ChooseCert(False)
  File "/usr/lib/python2.7/site-packages/gostcryptogui/gui.py", line 73, in __init__
    for line in certs_data:
  File "/usr/lib/python2.7/site-packages/gostcryptogui/cprocsp.py", line 142, in get_store_certs
    issuerCN = issuerDN['CN']
KeyError: 'CN'

Рутокен ЭЦП, КриптоПро v4.0.9006 KC1 Release Ver:4.0.9708, квалифицированный сертификат.

Ошибка очень напоминает https://github.com/bmakarenko/token-manager/issues/3

**Comment by sibskull** [comment]
У меня выдаёт диалог:  "Произошла ошибка:
'CN'"
При этом:
```
$ certmgr -list -store uMy
Certmgr 1.0 (c) "CryptoPro",  2007-2010.
program for managing certificates, CRLs and stores

=============================================================================                                                           
1-------                                                                                                                                
Issuer              : E=ca@skbkontur.ru, C=RU, S=66 Свердловская область, L=Екатеринбург, OU=Удостоверяющий центр, O=ЗАО «ПФ «СКБ Контур», CN=UC SKB Kontur (GT)                                                                                                                
Subject             : E=aen@basealt.ru, C=RU, S=г. Москва, L=Москва, O="ООО ""БАЗАЛЬТ СПО""", CN=Новодворский Алексей Евгеньевич, UnstructuredName="INN=7714350892/KPP=771401001/OGRN=1157746734837", T=Генеральный Директор, SN=Новодворский Алексей Евгеньевич                
Serial              : 0x1B73FED800050001C51E                                                                                            
SHA1 Hash           : 0x8f0bc81124f8cb9a79d5fd5818a6815a982aacdb                                                                        
SubjKeyID           : bccf85c16756e37c0f6edae342a8001e236185df                                                                          
Signature Algorithm : ГОСТ Р 34.11/34.10-2001                                                                                           
PublicKey Algorithm : ГОСТ Р 34.10-2001 (512 bits)                                                                                      
Not valid before    : 13/07/2016  12:03:00 UTC                                                                                          
Not valid after     : 13/07/2017  12:04:00 UTC                                                                                          
PrivateKey Link     : Yes                                                                                                               
Container           : SCARD\rutoken_lt_319a5c53\0B00\7566                                                                               
Provider Name       : Crypto-Pro GOST R 34.10-2001 KC1 CSP                                                                              
Provider Info       : ProvType: 75, KeySpec: 1, Flags: 0x0                                                                              
RFC #822 Name       : aen@basealt.ru                                                                                                    
Extended Key Usage  : 1.3.6.1.5.5.7.3.2                                                                                                 
                      1.2.643.2.2.34.6                                                                                                  
                      1.3.6.1.5.5.7.3.4                                                                                                 
                      1.2.643.6.3.1.2.1                                                                                                 
                      1.2.643.6.3.1.4.1                                                                                                 
                      1.2.643.6.3.1.4.2
                      1.2.643.6.3.1.4.3
                      1.2.643.6.3.1.3.1
                      1.2.643.6.3.1.1
                      1.2.643.3.7.5.70
                      1.2.643.3.7.0.1.12
=============================================================================

[ErrorCode: 0x00000000]
```

**Comment by bmakarenko** [comment]
Проблема была, судя по всему, в поле O=ЗАО «ПФ «СКБ Контур»
Регэксп не понимал франзуцкие кавычки "ёлочки"

**Comment by sibskull** [comment]
Это не французские, а русские правильные кавычки.

**Comment by sibskull** [comment]
после наложения патча:
Произошла ошибка:
'ascii' codec can't decode byte 0xd0 in position 126: ordinal not in range(128)

**Comment by sibskull** [comment]
Там в SubjectDN: UnstructuredName=, а findall только для букв в верхнем регистре.

**Comment by sibskull** [comment]
Но и до этого не доходит, так как спотыкается на первом пробеле в «CN=Новодворский »

**Comment by sibskull** [comment]
Не распарсивает 
```
UnstructuredName="INN=7714350892/KPP=771401001/OGRN=1157746734837"
```

**Comment by sibskull** [comment]
```
>>> c=u'E=aen@basealt.ru, C=RU, S=г. Москва, L=Москва, O="ООО ""БАЗАЛЬТ СПО""", CN=Новодворский Алексей Евгеньевич, UnstructuredName="INN=7714350892/KPP=771401001/OGRN=1157746734837", T=Генеральный Директор, SN=Новодворский Алексей Евгеньевич'
>>> for v in re.findall(ur'([A-Za-z0-9\.]+?)=("?[\xab\xbb\(\)\w \.\,0-9@\-\#\/\"]+"?)(?:, |$)', c, re.UNICODE):
...     print v[0], ' = ', v[1]
... 
E  =  aen@basealt.ru
C  =  RU
S  =  г. Москва
L  =  Москва
O  =  "ООО ""БАЗАЛЬТ СПО"""
CN  =  Новодворский Алексей Евгеньевич
OGRN  =  1157746734837"
T  =  Генеральный Директор
SN  =  Новодворский Алексей Евгеньевич
```

**Comment by bmakarenko** [comment]
Таки французкие. 
Допилил регэксп, теперь захватывается **все** символы, что попали в кавычки. Французские кавычки тоже распарсиваются.

```
>>> import re
>>> c=u'E=aen@basealt.ru, C=RU, S=г. Москва, L=Москва, O="ООО ""БАЗАЛЬТ СПО""", CN=Новодворский Алексей Евгеньевич, UnstructuredName="INN=7714350892/KPP=771401001/OGRN=1157746734837", T=Генеральный Директор, SN=Новодворский Алексей Евгеньевич'
>>> for v in re.findall(ur'([A-Za-z0-9\.]+?)=([\xab\xbb\(\)\w \.\,0-9@\-\#\/\"\/]+|\"(?:\\.|[^\"])*\")(?:, |$)', c, re.UNICODE):
...   print v[0], ' = ', v[1]
... 
E  =  aen@basealt.ru
C  =  RU
S  =  г. Москва
L  =  Москва
O  =  "ООО ""БАЗАЛЬТ СПО"""
CN  =  Новодворский Алексей Евгеньевич
UnstructuredName  =  "INN=7714350892/KPP=771401001/OGRN=1157746734837"
T  =  Генеральный Директор
SN  =  Новодворский Алексей Евгеньевич
>>> c=u'E=ca@skbkontur.ru, C=RU, S=66 Свердловская область, L=Екатеринбург, OU=Удостоверяющий центр, O=ЗАО «ПФ «СКБ Контур», CN=UC SKB Kontur (GT)'
>>> for v in re.findall(ur'([A-Za-z0-9\.]+?)=([\xab\xbb\(\)\w \.\,0-9@\-\#\/\"\/]+|\"(?:\\.|[^\"])*\")(?:, |$)', c, re.UNICODE):
...   print v[0], ' = ', v[1]
... 
E  =  ca@skbkontur.ru
C  =  RU
S  =  66 Свердловская область
L  =  Екатеринбург
OU  =  Удостоверяющий центр
O  =  ЗАО «ПФ «СКБ Контур»
CN  =  UC SKB Kontur (GT)
```

**Comment by wolneykien** [comment]
Отличная новость. Но есть предложение:

1. разбиваем строку на токены по разделителю «запятая + пробел»;
2. разбиваем токен на имя и значение по первому знаку равенства;
3. если в значении обнаружена открывающая кавычка (одинарная, двойная, французская, японская), но не обнаружена закрывающая, то прибавляем к нему следующий токен целиком;
4. повторяем шаг 3 до тех пор, пока выражение не будет содержать обе кавычки.

Так будет надёжнее и более контролируемо.

**Comment by bmakarenko** [comment]
Нет, такой алгоритм не подойдет. Потому что часто бывают поля вида:
STREET="ул. Пушкина, д. Колотушкина, корп. 2, стр. 1",
Получится такая фигня
```
>>> a = u'STREET="ул. Пушкина, д. Колотушкина, корп. 2, стр. 1",'
>>> for b in a.split(', '):
...   print b
... 
STREET="ул. Пушкина
д. Колотушкина
корп. 2
стр. 1",
```

**Comment by wolneykien** [comment]
Ну, я ошибся чуток. В п.3 не просто «прибавляем к нему следующий токен целиком», а «прибавляем к нему ", " и следующий токен целиком». Алгоритмический подход удобен тем, что можно довольно просто разные исключительные случаи обрабатывать.

**Comment by bmakarenko** [comment]
Опять же, как тогда быть с полями вида:
O="ООО ""БАЗАЛЬТ СПО"""
или
CN="УЦ ОАО ""Сбербанк России"""

Только регэкспы. Только хардкор!

**Comment by wolneykien** [comment]
Так ведь тут запятых нет — это один токен.
Однако я думаю, что разговор всё равно откладывается до следующей баги в регекспе. ;-)

**Comment by sibskull** [comment]
Осталось перенести фиксы из token-manager.

**Comment by sibskull** [comment]
трассировка:
```
cprocsp.py(168):             notValidBefore = cert[3]
cprocsp.py(169):             notValidAfter = cert[4]
cprocsp.py(170):             yield dict(issuerDN=issuerDN, issuerCN=issuerCN, subjectDN=subjectDN, subjectCN=subjectCN,
cprocsp.py(171):                        secretKey=secretKey, thumbprint=thumbprint, notValidBefore=notValidBefore,
cprocsp.py(172):                        notValidAfter=notValidAfter)
gui.py(76):             if withsecret and line['secretKey'] == 'Yes':
gui.py(77):                     cert_list.append(
gui.py(78):                         u'%s, \nВыдан:%s, \nХэш SHA1: %s\nНе действителен до: %s\nНе действителен после: %s' % (
gui.py(79):                             line['subjectCN'], line['issuerCN'], line['thumbprint'], line['notValidBefore'],
gui.py(80):                             line['notValidAfter']))
gui.py(221):         except Exception as error:
gui.py(222):             QtGui.QMessageBox().warning(self, u"Cообщение", u"Произошла ошибка:\n%s" % error)
```

Диалоговое окно: 'ascii' codec can't decode byte 0xd0 in position 126: ordinal not in range(128)

**Comment by bmakarenko** [comment]
Тут, видимо другая проблема. Уже другой регэксп не правильно распарсивал sha-хэш сертификата.

**Comment by sibskull** [comment]
Да, теперь работает, можно закрывать.
